name: Reusable

on:
  workflow_call:
    inputs:
      command:
        description: 'build command'
        required: true
        type: string
jobs:
  reusable:
    runs-on: ubuntu-latest
    env:
      command: ${{inputs.command}}
    steps:
        - name: Checkout Repo
          uses: actions/checkout@v3
        - name: run command
          run: |
            ${{ env.command }}
            ${{ env.command }}
  
